services:
  db:
    image: ${POSTGRES_IMAGE:-postgres:17.4} 
    hostname: koshi-db
    container_name: koshi-db
    profiles: ["pg", "all"]
    networks:
      - koshi-backend
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${KOSHI_POSTGRES_USER}
      POSTGRES_DB: ${KOSHI_POSTGRES_DB}
      POSTGRES_PASSWORD: ${KOSHI_POSTGRES_PASSWORD}
      PGPASSWORD: ${KOSHI_PGPASSWORD}
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped
