services:
  mailcrab:
    image: marlonb/mailcrab:latest
    container_name: koshi-mailcrab
    hostname: koshi-mailcrab
    profiles: ["mailcrab", "all"]
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - koshi-backend
