services:
  dozzle:
    image: amir20/dozzle:latest
    hostname: dozzle
    container_name: dozzle
    profiles: ["dozzle", "all"]
    networks: 
      - koshi-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - koshi-dozzle:/data
    restart: unless-stopped
volumes:
  koshi-dozzle:
