# TODO: looks like https://github.com/postgis/docker-postgis/issues/216 should be closed soon
services:
  db:
    image: ${POSTGRES_IMAGE:-imresamu/postgis:17-3.4-alpine}
    hostname: koshi-db
    container_name: koshi-db
    profiles: ["pg", "all"]
    networks:
      - koshi-backend
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      #   POSTGRES_DB: ${KOSHI_POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_KOSHI_DB: ${POSTGRES_KOSHI_DB}
      POSTGRES_KOSHI_USER: ${POSTGRES_KOSHI_USER}
      POSTGRES_KOSHI_PASSWORD: ${POSTGRES_KOSHI_PASSWORD}
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped
