services:
  redis:
    image: ${REDIS_IMAGE:-redis:7.4.2}
    hostname: koshi-redis
    container_name: koshi-redis
    profiles: ["redis", "all"]
    ports:
      - "6379:6379"
    networks: 
      - koshi-backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped